# Site settings
title: Michelle Halevi
email: michelle@michellehalevi.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/michellehalevi.github.io" # the subpath of your site, e.g. /blog/
url: "http://michellehalevi.github.io" # the base hostname & protocol for your site
twitter_username: michfaace
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
